### ISSUE TITLE
Peer to peer week 4 Day 5

### ISSUE THREAD

**Issue by MuhammadUsmanAslam** [shubhambhoyar077/portfolio#15]
- I think there is some repetitive code in CSS that is against the DRY rule. @MuhammadUsmanAslam
- In popup/modal button alignment is not the same as the Figma design. @MuhammadUsmanAslam
- [Optional] I think the navbar should be position fixed when we scroll the window. @MuhammadUsmanAslam

**Comment by shubhambhoyar077** [comment]
Fix the above issues
