### ISSUE TITLE
Bug hide and seek

### ISSUE THREAD

**Issue by lengushuru** [shubhambhoyar077/portfolio#16]
**Great work implementing all the project requirements, please check on this bugs**

- Found typo in variable name in https://github.com/shubhambhoyar077/portfolio/blob/938a114f3fc6cc32c1e20413a26ab632fde61f1c/js/script.js#L2
variable name should be mobileMenu.

- This function https://github.com/shubhambhoyar077/portfolio/blob/938a114f3fc6cc32c1e20413a26ab632fde61f1c/js/script.js#L213 should come before update local storage.

- found typo in variable name at line https://github.com/shubhambhoyar077/portfolio/blob/938a114f3fc6cc32c1e20413a26ab632fde61f1c/js/script.js#L176 .

**Comment by shubhambhoyar077** [comment]
fix bugs
